import { useCallback, useEffect, useState } from "react";
import { api, type AppConfig, type OwnerMapRow, type OwnerStatusRow, type PortfolioInfo } from "../lib/api";
import { fmt, fmtDate, fmtMonth } from "../lib/format";

const ORIGIN_LABEL = { mapping: "Owner map", feed: "CMDB feed only", system: "System" } as const;

export function MappingTab({ config, onReset }: { config: AppConfig; onReset: () => void }) {
  const [portfolios, setPortfolios] = useState<PortfolioInfo[]>([]);
  const [ownerMap, setOwnerMap] = useState<OwnerMapRow[]>([]);
  const [owners, setOwners] = useState<OwnerStatusRow[]>([]);
  const [msg, setMsg] = useState<{ tone: string; text: string } | null>(null);
  const [newMap, setNewMap] = useState({ owner: "", portfolio: "" });
  const [busy, setBusy] = useState(false);

  const load = useCallback(() => {
    Promise.all([api.portfolios(), api.ownerMap(), api.ownerStatus()])
      .then(([p, m, o]) => {
        setPortfolios(p);
        setOwnerMap(m);
        setOwners(o);
      })
      .catch((e) => setMsg({ tone: "bad", text: e.message }));
  }, []);
  useEffect(load, [load]);

  const assignable = portfolios.filter((p) => p.origin === "mapping");
  const unmappedOwners = owners.filter((o) => !ownerMap.some((m) => m.owner === o.username));

  const run = async (fn: () => Promise<string>) => {
    setBusy(true);
    try {
      setMsg({ tone: "ok", text: await fn() });
      load();
    } catch (e) {
      setMsg({ tone: "bad", text: (e as Error).message });
    } finally {
      setBusy(false);
    }
  };

  const reset = () => {
    if (!confirm("Reset the demo? This discards every plan edit, import and mapping change and restores the original dataset.")) return;
    run(async () => {
      await api.resetDemo();
      onReset();
      return "Demo data restored.";
    });
  };

  return (
    <div className="mapping">
      {msg && <div className={`status ${msg.tone}`}>{msg.text}</div>}

      <div className="two-col">
        <section className="card section">
          <h3>Program settings</h3>
          <table className="table compact kv">
            <tbody>
              <tr><th>Tracked OS</th><td>{config.tracked_os.join(", ")}</td></tr>
              <tr><th>Reporting window</th><td>{fmtMonth(config.months[0])} to {fmtMonth(config.months[config.months.length - 1])}</td></tr>
              <tr><th>Baseline date</th><td>{fmtDate(config.baseline_date)}</td></tr>
              <tr><th>Data as of</th><td>{fmtDate(config.as_of)}</td></tr>
              <tr><th>On-track checkpoint</th><td>end of {fmtMonth(config.checkpoint_month)} (last completed month)</td></tr>
              <tr><th>Actuals source</th><td>{config.source}</td></tr>
            </tbody>
          </table>
          <p className="muted small">Read-only in the demo. In the original tool these were configured per program.</p>
        </section>

        <section className="card section">
          <h3>Demo data</h3>
          <p>
            Everything in Horizon is synthetic: hosts, owners and plans are generated by a seeded script, so the dataset is
            identical on every install. Edits you make are saved to the local database.
          </p>
          <button className="btn danger" disabled={busy} onClick={reset}>Reset demo data</button>
        </section>
      </div>

      <section className="card section">
        <h3>Portfolios</h3>
        <p className="muted small">
          A host's portfolio comes from the CMDB feed when present; otherwise from the owner map below; otherwise it lands in
          Unknown.
        </p>
        <table className="table compact">
          <thead>
            <tr>
              <th>Short name</th><th>Full name</th><th>Known from</th><th className="num">Mapped owners</th>
              {config.tracked_os.map((o) => <th key={o} className="num">{o} remaining</th>)}
            </tr>
          </thead>
          <tbody>
            {portfolios.map((p) => (
              <tr key={p.code}>
                <td><b>{p.code}</b></td>
                <td>{p.full_name}</td>
                <td><span className="tag">{ORIGIN_LABEL[p.origin]}</span></td>
                <td className="num">{fmt(p.mapped_owners)}</td>
                {config.tracked_os.map((o) => <td key={o} className="num">{fmt(p.remaining[o] ?? 0)}</td>)}
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <section className="card section">
        <h3>Owner → portfolio map <span className="count-pill">{ownerMap.length}</span></h3>
        <div className="toolbar">
          <select value={newMap.owner} onChange={(e) => setNewMap({ ...newMap, owner: e.target.value })}>
            <option value="">Unmapped owner…</option>
            {unmappedOwners.map((o) => <option key={o.username} value={o.username}>{o.username} ({o.display_name})</option>)}
          </select>
          <select value={newMap.portfolio} onChange={(e) => setNewMap({ ...newMap, portfolio: e.target.value })}>
            <option value="">Portfolio…</option>
            {assignable.map((p) => <option key={p.code} value={p.code}>{p.code}</option>)}
          </select>
          <button
            className="btn primary"
            disabled={busy || !newMap.owner || !newMap.portfolio}
            onClick={() => run(async () => {
              const r = await api.setOwnerMap(newMap.owner, newMap.portfolio);
              setNewMap({ owner: "", portfolio: "" });
              return `Mapped ${newMap.owner} → ${newMap.portfolio} (${r.hosts_updated} hosts re-assigned).`;
            })}
          >
            Add mapping
          </button>
        </div>
        <div className="scroll-table">
          <table className="table compact">
            <thead>
              <tr><th>Owner</th><th>Name</th><th>Portfolio</th><th /></tr>
            </thead>
            <tbody>
              {ownerMap.map((m) => (
                <tr key={m.owner}>
                  <td className="mono">{m.owner}</td>
                  <td>{m.display_name}</td>
                  <td>
                    <select
                      disabled={busy}
                      value={m.portfolio}
                      onChange={(e) => run(async () => {
                        const r = await api.setOwnerMap(m.owner, e.target.value);
                        return `${m.owner} → ${e.target.value} (${r.hosts_updated} hosts re-assigned).`;
                      })}
                    >
                      {assignable.map((p) => <option key={p.code} value={p.code}>{p.code}</option>)}
                    </select>
                  </td>
                  <td>
                    <button
                      className="btn small danger"
                      disabled={busy}
                      onClick={() => run(async () => {
                        const r = await api.deleteOwnerMap(m.owner);
                        return `Removed ${m.owner}'s mapping (${r.hosts_updated} hosts moved to Unknown).`;
                      })}
                    >
                      Remove
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="card section">
        <h3>Owner status</h3>
        <p className="muted small">Departed owners are flagged on the Actuals tab until their hosts get a new owner.</p>
        <div className="scroll-table">
          <table className="table compact">
            <thead>
              <tr><th>Owner</th><th>Name</th><th>First seen</th><th>Status</th><th>Note</th></tr>
            </thead>
            <tbody>
              {owners.map((o) => (
                <tr key={o.username}>
                  <td className="mono">{o.username}</td>
                  <td>{o.display_name}</td>
                  <td>{fmtDate(o.first_seen)}</td>
                  <td>
                    <select
                      disabled={busy}
                      value={o.status}
                      className={o.status === "departed" ? "text-bad" : ""}
                      onChange={(e) => run(async () => {
                        await api.setOwnerStatus(o.username, e.target.value, o.note);
                        return `${o.username} marked ${e.target.value}.`;
                      })}
                    >
                      <option value="active">active</option>
                      <option value="departed">departed</option>
                      <option value="unknown">unknown</option>
                    </select>
                  </td>
                  <td className="muted small">{o.note ?? ""}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
}
